GET http://localhost:5000/v1/api/talents

###
GET http://localhost:5000/v1/api/talents/kaela-kovalskia

###
GET http://localhost:5000/v1/api/list/council


###
GET http://localhost:5000/v1/api/stream
